dist: bionic
language: c
addons:
  apt:
    packages:
     - libfftw3-dev
     - libgconf2-dev
     - libgtk-3-dev
     - libgtk-3-common
     - libgtk-3-0
     - libjpeg-dev
     - libtiff-dev
     - liblcms2-dev
     - libcurl4-gnutls-dev
     - libexiv2-dev
     - libflickcurl-dev
     - libsqlite3-dev
     - libgphoto2-dev
#     - libgphoto2-dev-doc
#     - libgphoto2-2-dev
     - autopoint
     - autoconf
     - automake
     - gettext
     - libtool-bin
     - liblensfun-dev
#     - libosmgpsmap-dev
     - libsoup2.4-dev

before_install:

before_script:
   - ./autogen.sh --no-configure

script:
  - ./configure --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-static --enable-experimental --enable-maintainer-mode
  - make all
